[tool.poetry]
name = "my-awesome-project"
version = "0.1.0"
description = "A brief description of the project"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
