repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0 # Use the git tag for the version you need
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 21.5b2 # The version of Black you want to use
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/prettier/prettier
    rev: "2.3.0" # The version of Prettier you want to use
    hooks:
      - id: prettier
        exclude: '^docs/'
